version = 0.1

[default.build.parameters]
use_container = false
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "vd-speedtest-stack"
region = "ap-south-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
confirm_changeset = false
s3_bucket = "vd-speed-test"
image_repositories = []
s3_prefix = "vd-speedtest-stack"